### ISSUE TITLE
Windows resize when using maliit

### ISSUE THREAD

**Issue by thephatmaster** [maliit/framework#113]
I hope this is the right place. I'm using maliit (the only option AFAIK) on my Surface Go, running KDE Neon (20.04 based) in a Wayland session.

When maliit is used, often windows get smaller to accomodate it (Konsole and Firefox both do this), but then do not return to full size.

**Comment by dobey** [comment]
Maliit itself does not directly modify other windows, so this is more likely an issue in kwin, which you can open an issue against at https://bugs.kde.org to track it. Thanks.
