### ISSUE TITLE
Build is broken

### ISSUE THREAD

**Issue by mightyCelu** [maliit/framework#16]
When cloning the repository and running qmake I get only this output:
> Tip: Run qmake HELP=1 for a list of all supported build options

**Comment by attente** [comment]
I think that's only an informational message; after running qmake, the project still generates a Makefile in the top-level directory which you can build the project with by just calling 'make'.

**Comment by mightyCelu** [comment]
Oh, you're right. My bad.

**Comment by mightyCelu** [comment]
I still have issues getting it to build properly. When I use something like PREFIX=$HOME/somewhere
I get errors while running make install, apparently some headers are tried to copy to /usr/include and when I circumvent that by manually setting the include dir it tries to copy to /usr/share/qt/mkspecs.
Is this intended?

**Comment by jpetersen** [comment]
It tries to install some stuff into Qt plugin and Qt mkspecs directories. Because that is where Qt/qmake will look for them. But yes for development another solution would be better.

**Comment by attente** [comment]
I found that setting CONFIG+=local-install in the qmake command line prevented it from installing outside of the PREFIX, for me at least.

**Comment by jpetersen** [comment]
Ah yes we have that option for that purpose.

**Comment by mightyCelu** [comment]
Ah nice, now it is working for me. I must say though that I find it weird that the prefix is not by default enforced for all files.
