### ISSUE TITLE
Incompatible with windows and msvc

### ISSUE THREAD

**Issue by RHawkeyed** [maliit/framework#24]
There is a couple of things that are not compatible with msvc or microsoft windows in general. 

I have successfully modified it to compile on windows. Since you are now active again I would like to submit it. However it is a bit messy at the moment, so before I try to make it merge ready, I would like to know if you are still interested in having windows compatibility?

Also I am not very experienced in git yet. A single branch of commits with a commit per compatibility issue would be the way to go or?

**Comment by jpetersen** [comment]
Yes, we are still interested in having windows compatibility.

Yes having one commit per issue would be great.

**Comment by RHawkeyed** [comment]
Hi again, in case anyone is waiting for this, sorry it's taking so long. Something else came up and now I'm going on vacation. If current plans hold I will have time for this the first week of January.

**Comment by dobey** [comment]
It's not clear that Maliit would even work on Windows, or that we should necessarily support it at this time, and I've closed the PR as it's been sitting for so long. If there's a good reason to support Maliit on Windows now, perhaps we can look at making it possible, and in a cleaner and more testable way. Thanks!
