### ISSUE TITLE
How to run Maliit on Ubuntu?

### ISSUE THREAD

**Issue by kq01526** [maliit/framework#32]
Hi,

Maliit is available in the Ubuntu repositories, see:

http://packages.ubuntu.com/search?keywords=maliit&searchon=names&suite=all&section=all

However, for some reason it does not seem to start.

This might be a dumb question, but:

How do you actually use Maliit on Ubuntu? Can not get it to open :worried:.

Looks like lot of other people have the same issue, see:

https://ubuntuforums.org/showthread.php?t=2316415
http://askubuntu.com/questions/709269/maliit-on-screen-keyboard
http://askubuntu.com/questions/421173/maliit-onscreen-keyboard-installed-on-msi-windpad-110w-tablet-in-saucy-but-will
http://stackoverflow.com/questions/33256854/how-to-get-maliit-keyboard-working-on-linux-mint

Any chance you could help?

Regards

**Comment by kq01526** [comment]
Anyone?

**Comment by jpetersen** [comment]
Not sure it exists there even anymore.
