### ISSUE TITLE
Segmentation fault maliit-server

### ISSUE THREAD

**Issue by cagnulein** [maliit/framework#38]
I've build the framework and the keyboard succesfully on Ubuntu and Archlinux both, but when i try to run the maliit-server it always hangs. Do you have an idea?
maliit-keyboard doesn't crash, but the keyboard doesn't never appear.
Thanks

<pre>
[sysele@sysele-pc keyboard]$ ./maliit-keyboard
qt5ct: using qt5ct plugin
wordengine.cpp plugin "/usr/local/share/maliit/plugins/org/maliit/lib/en/libenplugin.so" loaded
inputmethod_p.h registerActiveLanguage(): activeLanguage is: "en"
in inputMethod.cpp setActiveLanguage() activeLanguage is: "en"
spellechecker.cpp in setLanguage() lang= "en" dictPath= "/usr/share/myspell"
Did not find a dictionary for "en"  - checking for  "en"
No dictionary found for "en" turning off spellchecking
no dictionary to turn on spellchecking
inputMethod::reset()
in clear preedit.. clearing word engine
file:///usr/local/share/maliit/plugins/org/maliit/lib/en/Keyboard_en.qml:66:13: Type ShiftKey unavailable
file:///usr/local/share/maliit/plugins/org/maliit/keys/ShiftKey.qml:23:1: Type ActionKey unavailable
file:///usr/local/share/maliit/plugins/org/maliit/keys/ActionKey.qml:20:1: module "QtGraphicalEffects" is not installed
keyboard is reporting <x y w h>: < 0 -8 0 8 > to the app manager.
QSoundEffect(pulseaudio): Error decoding source /usr/share/maliit/plugins/org/maliit/styles/ubuntu/sounds/key_tick2_quiet.wav
keyboard is reporting <x y w h>: < 0 892 0 8 > to the app manager.
keyboard is reporting <x y w h>: < 0 451 0 449 > to the app manager.
keyboard is reporting <x y w h>: < 0 10 0 890 > to the app manager.
keyboard is reporting <x y w h>: < 0 451 0 449 > to the app manager.
keyboard is reporting <x y w h>: < 0 586 0 314 > to the app manager.
keyboard is reporting <x y w h>: < 0 721 0 179 > to the app manager.
keyboard is reporting <x y w h>: < 0 586 0 314 > to the app manager.
keyboard is reporting <x y w h>: < 0 586 1440 314 > to the app manager.
^C
[sysele@sysele-pc keyboard]$ cd ..
[sysele@sysele-pc maliit]$ cd framework/
[sysele@sysele-pc framework]$ ./maliit-server
CRITICAL: "wordengine.cpp - loading plugin failed: /usr/local/share/maliit/plugins/org/maliit/lib/en/libenplugin.so"
WARNING: virtual void MaliitKeyboard::Logic::WordEngine::setWordPredictionEnabled(bool) No backend available, cannot enable word engine!
Errore di segmentazione (core dump creato)
</pre>

**Comment by jpetersen** [comment]
QtGraphicalEffects need to be installed

**Comment by jpetersen** [comment]
maliit-server seems to not be able to find its plugins not sure why it crashes without s stacktrace.

**Comment by jpetersen** [comment]
Not a bug. But missing dependency. Documentation could be improved though.
