### ISSUE TITLE
Tag a new release

### ISSUE THREAD

**Issue by PureTryOut** [maliit/framework#46]
Lately I've been packaging Maliit for [postmarketOS](https://postmarketos.org) so it can be used together with [Plasma Mobile](https://plasma-mobile.org). Normally I just take the latest release, however it seems that in this case this means using a version from the 13th of November 2015, even though development has been active ever since with the latest commits being done only a day ago.

This makes me wonder, would it be possible to tag a new release anytime soon? For one the old release still uses qmake while the master branch seems to have used CMake for quite a while already.

**Comment by jpetersen** [comment]
I think it makes sense to tag a release now. If there are more changes will create just another release

**Comment by KAMiKAZOW** [comment]
Why not release 1.0 already?
