### ISSUE TITLE
Support text-input-unstable-v2 ?

### ISSUE THREAD

**Issue by bhush9** [maliit/framework#47]
My understanding is that maliit currently uses the text-input-unstable-v1, however Qt uses slightly different version (and not upstream'd) version of it text-input-unstable-v2 : https://github.com/qt/qtwayland/blob/5.15.1/src/3rdparty/protocol/text-input-unstable-v2.xml

Would it make sense to add support for text-input-unstable-v2? As far as I know no clients currently use the v1 of protocol, and v0, v2 or v3 are the only ones used.

**Comment by bhush9** [comment]
Okay, seems duplicate of #25

**Comment by jpetersen** [comment]
As commented in #25 it requires first a wayland compositor to be willing to implement some new protocol (input-method v?).

The compositor could of course also communicate to maliit via DBus protocol and support text-input v1, v2 and/or v3 for all kind of clients.
