### ISSUE TITLE
Segmentation fault on i.MX6

### ISSUE THREAD

**Issue by smanni-et** [maliit/framework#50]
On an i.MX6 processore running linux 4.1.15 and Qt 5.9.7 maliit-server crashes with SIGSEGV just after the startup. 

Here is the complete log: https://gist.github.com/smanni-et/8a18911de49baa07da6c2aed30700671
Here is the output from gdb: https://gist.github.com/smanni-et/8156abeab4b5ba21e79bbc90b68869fb

Someone in the past discovered something similar (#38) but the issue has been closed as invalid. 

Found on ee7d872

**Comment by dobey** [comment]
Is this still an issue with latest framework? Can you get a more detailed stack trace if so? Thanks!

**Comment by smanni-et** [comment]
Why did you close it? I didn't have the chance to test it.

Do you have any idea why this issue should have been fixed in the latest version?

**Comment by smanni-et** [comment]
The bug is still there in 2.1.1

**Comment by dobey** [comment]
If this is still a problem with 2.2.0, what keyboard plug-in are you using with maliit here? Are you using https://github.com/maliit/keyboard ? or some other plugin?
