### ISSUE TITLE
Problem compiling: Parse error at "IID"

### ISSUE THREAD

**Issue by surprized** [maliit/framework#51]
Hello, I am getting this error while compiling:
`[  112s] AutoMoc subprocess error`
`[  112s] ------------------------`
`[  112s] The moc process failed to compile`
`[  112s]   "SRC:/src/qt/plugins/shellintegration/inputpanelshellplugin.cpp"`
`[  112s] into`
`[  112s]   "SRC:/build/inputpanel-shell_autogen/include/inputpanelshellplugin.moc"`
`[  112s] included by`
`[  112s]   "SRC:/src/qt/plugins/shellintegration/inputpanelshellplugin.cpp"`
`[  112s] /home/abuild/rpmbuild/BUILD/framework-1601419413.ee7d872/src/qt/plugins/shellintegration/inputpanelshellplugin.cpp:23: Parse error at "IID"`

I attached the full log for reference.
I can't tell if it's a bug or something I doing wrong on my end. Please help me.
Packaging progress can be seen at https://build.opensuse.org/package/show/home:andresbs:maliit/maliit-framework

[log.log](https://github.com/maliit/framework/files/5779085/log.log)

**Comment by surprized** [comment]
Plasma Mobile people helped me on this one
I had to add the following to the specfile:

`BuildRequires:  libQt5Gui-private-headers-devel`
`BuildRequires:  pkgconfig(xkbcommon)`
`BuildRequires:  libqt5-qtwayland-private-headers-devel`

Also I needed to create external variables:
`export xkbcommon_includes=$(pkg-config xkbcommon --variable=includedir)`
`export wayland_private_headers_devel_includes=$(pkg-config wayland-client --variable=includedir)`

And then add this to the **bottom** of the  `CMakeLists.txt`:
`target_include_directories(inputpanel-shell PUBLIC $ENV{wayland_private_headers_devel_includes})`
`target_include_directories(inputpanel-shell PUBLIC $ENV{xkbcommon_includes})`
`target_include_directories(maliit-common PUBLIC $ENV{xkbcommon_includes})`

This two steps were needed due to weird openSUSE packaging.
I'll leave it here if someone comes across it in the future.

**Comment by Semperverus** [comment]
I am running into this issue on Debian Testing (Bullseye, i386 architecture) as well, and trying these recommendations did not fix the issue (obviously leaving out the suse-specific steps for the BuildRequires spec file thing).

I made sure to pull in build dependencies by doing `sudo apt build-dep kwin-wayland`
and fixed the qtwaylandscanner not found issue by adding /usr/sh

Basically getting an almost identical error:
```Scanning dependencies of target inputpanel-shell_autogen
[ 43%] Automatic MOC for target inputpanel-shell

AutoMoc subprocess error
------------------------
The moc process failed to compile
  "SRC:/src/qt/plugins/shellintegration/inputpanelshellplugin.cpp"
into
  "SRC:/build/inputpanel-shell_autogen/include/inputpanelshellplugin.moc"
included by
  "SRC:/src/qt/plugins/shellintegration/inputpanelshellplugin.cpp"

Command
-------
/usr/lib/qt5/bin/moc -DHAVE_WAYLAND "-DMALIIT_CONFIG_ROOT=\"/maliit/\"" "-DMALIIT_DEFAULT_HW_PLUGIN=\"libmaliit-keyboard-plugin.so\"" "-DMALIIT_DEFAULT_PLUGIN=\"libmaliit-keyboard-plugin.so\"" "-DMALIIT_DEFAULT_SUBVIEW=\"\"" -DMALIIT_ENABLE_MULTITOUCH=true "-DMALIIT_EXTENSIONS_DIR=\"/usr/share/maliit-framework/extensions\"" -DMALIIT_FRAMEWORK_USE_INTERNAL_API "-DMALIIT_PLUGINS_DATA_DIR=\"/usr/share/maliit/plugins\"" "-DMALIIT_PLUGINS_DIR=\"/usr/lib/i386-linux-gnu/maliit/plugins\"" -DQT_CORE_LIB -DQT_GUI_LIB -DQT_NO_DEBUG -DQT_WAYLANDCLIENT_LIB -Dinputpanel_shell_EXPORTS -I/home/semperverus/framework/build -I/home/semperverus/framework -I/home/semperverus/framework/src -I/home/semperverus/framework/common -I/usr/include/i386-linux-gnu/qt5/QtGui/5.15.2 -I/usr/include/i386-linux-gnu/qt5/QtGui/5.15.2/QtGui -I/usr/include/i386-linux-gnu/qt5/QtCore/5.15.2 -I/usr/include/i386-linux-gnu/qt5/QtCore/5.15.2/QtCore -I/usr/include/i386-linux-gnu/qt5/QtWaylandClient/5.15.2 -I/usr/include/i386-linux-gnu/qt5/QtWaylandClient/5.15.2/QtWaylandClient -I/usr/include/i386-linux-gnu/qt5/QtXkbCommonSupport/5.15.2 -I/usr/include/i386-linux-gnu/qt5/QtXkbCommonSupport/5.15.2/QtXkbCommonSupport -I/usr/include/i386-linux-gnu/qt5 -I/usr/include/i386-linux-gnu/qt5/QtWaylandClient -I/usr/include/i386-linux-gnu/qt5/QtGui -I/usr/include/i386-linux-gnu/qt5/QtCore -I/usr/lib/i386-linux-gnu/qt5/mkspecs/linux-g++ -I/usr/include -I/usr/include/c++/10 -I/usr/include/i386-linux-gnu/c++/10 -I/usr/include/c++/10/backward -I/usr/lib/gcc/i686-linux-gnu/10/include -I/usr/local/include -I/usr/include/i386-linux-gnu --include /home/semperverus/framework/build/inputpanel-shell_autogen/moc_predefs.h --output-dep-file -o /home/semperverus/framework/build/inputpanel-shell_autogen/include/inputpanelshellplugin.moc /home/semperverus/framework/src/qt/plugins/shellintegration/inputpanelshellplugin.cpp

Output
------
/home/semperverus/framework/src/qt/plugins/shellintegration/inputpanelshellplugin.cpp:23: Parse error at "IID"

make[2]: *** [CMakeFiles/inputpanel-shell_autogen.dir/build.make:77: CMakeFiles/inputpanel-shell_autogen] Error 1
make[1]: *** [CMakeFiles/Makefile2:995: CMakeFiles/inputpanel-shell_autogen.dir/all] Error 2
make: *** [Makefile:160: all] Error 2```

Verifying the recommended fixes:
When I run `echo $(pkg-config xkbcommon --variable=includedir)` it points to `/usr/include`
When I run `echo $(pkg-config wayland-client --variable=includedir)` it also points to `/usr/include`
Both files that the commands in @surprized's suggested fixes are indeed available in there (there's a folder for xkbcommon, and there are fiels for wayland-client).

Is there anything else I should be looking at for clues on how to fix this, or does anyone maybe know what is causing it?

**Comment by M-Kerr** [comment]
> I am running into this issue on Debian Testing (Bullseye, i386 architecture) as well, and trying these recommendations did not fix the issue (obviously leaving out the suse-specific steps for the BuildRequires spec file thing). I've tried with both the 2.0.0 release and with the Master branch. Cleared out the build folder on many attempts after changes as well, and started completely from scratch a few times.
> 
> I made sure to pull in all build dependencies (and then some) by doing `sudo apt build-dep kwin-wayland` and fixed the qtwaylandscanner not found issue by adding `/usr/lib/i386-linux-gnu/qt5/bin/` to PATH (using `export PATH=$PATH:/usr/lib/i386-linux-gnu/qt5/bin`, for 64 bit systems you'd use `/usr/lib/qt5/bin/` instead).
> 
> Basically getting an almost identical error:
> 
> ```
> [ 43%] Automatic MOC for target inputpanel-shell
> 
> AutoMoc subprocess error
> ------------------------
> The moc process failed to compile
>   "SRC:/src/qt/plugins/shellintegration/inputpanelshellplugin.cpp"
> into
>   "SRC:/build/inputpanel-shell_autogen/include/inputpanelshellplugin.moc"
> included by
>   "SRC:/src/qt/plugins/shellintegration/inputpanelshellplugin.cpp"
> 
> Command
> -------
> /usr/lib/qt5/bin/moc -DHAVE_WAYLAND "-DMALIIT_CONFIG_ROOT=\"/maliit/\"" "-DMALIIT_DEFAULT_HW_PLUGIN=\"libmaliit-keyboard-plugin.so\"" "-DMALIIT_DEFAULT_PLUGIN=\"libmaliit-keyboard-plugin.so\"" "-DMALIIT_DEFAULT_SUBVIEW=\"\"" -DMALIIT_ENABLE_MULTITOUCH=true "-DMALIIT_EXTENSIONS_DIR=\"/usr/share/maliit-framework/extensions\"" -DMALIIT_FRAMEWORK_USE_INTERNAL_API "-DMALIIT_PLUGINS_DATA_DIR=\"/usr/share/maliit/plugins\"" "-DMALIIT_PLUGINS_DIR=\"/usr/lib/i386-linux-gnu/maliit/plugins\"" -DQT_CORE_LIB -DQT_GUI_LIB -DQT_NO_DEBUG -DQT_WAYLANDCLIENT_LIB -Dinputpanel_shell_EXPORTS -I/home/semperverus/maliit/framework/build -I/home/semperverus/maliit/framework -I/home/semperverus/maliit/framework/src -I/home/semperverus/maliit/framework/common -I/usr/include/i386-linux-gnu/qt5/QtGui/5.15.2 -I/usr/include/i386-linux-gnu/qt5/QtGui/5.15.2/QtGui -I/usr/include/i386-linux-gnu/qt5/QtCore/5.15.2 -I/usr/include/i386-linux-gnu/qt5/QtCore/5.15.2/QtCore -I/usr/include/i386-linux-gnu/qt5/QtWaylandClient/5.15.2 -I/usr/include/i386-linux-gnu/qt5/QtWaylandClient/5.15.2/QtWaylandClient -I/usr/include/i386-linux-gnu/qt5/QtXkbCommonSupport/5.15.2 -I/usr/include/i386-linux-gnu/qt5/QtXkbCommonSupport/5.15.2/QtXkbCommonSupport -I/usr/include/i386-linux-gnu/qt5 -I/usr/include/i386-linux-gnu/qt5/QtWaylandClient -I/usr/include/i386-linux-gnu/qt5/QtGui -I/usr/include/i386-linux-gnu/qt5/QtCore -I/usr/lib/i386-linux-gnu/qt5/mkspecs/linux-g++ -I/usr/include -I/usr/include/c++/10 -I/usr/include/i386-linux-gnu/c++/10 -I/usr/include/c++/10/backward -I/usr/lib/gcc/i686-linux-gnu/10/include -I/usr/local/include -I/usr/include/i386-linux-gnu --include /home/semperverus/maliit/framework/build/inputpanel-shell_autogen/moc_predefs.h --output-dep-file -o /home/semperverus/maliit/framework/build/inputpanel-shell_autogen/include/inputpanelshellplugin.moc /home/semperverus/maliit/framework/src/qt/plugins/shellintegration/inputpanelshellplugin.cpp
> 
> Output
> ------
> /home/semperverus/maliit/framework/src/qt/plugins/shellintegration/inputpanelshellplugin.cpp:23: Parse error at "IID"
> 
> make[2]: *** [CMakeFiles/inputpanel-shell_autogen.dir/build.make:77: CMakeFiles/inputpanel-shell_autogen] Error 1
> make[1]: *** [CMakeFiles/Makefile2:995: CMakeFiles/inputpanel-shell_autogen.dir/all] Error 2
> make: *** [Makefile:160: all] Error 2
> ```
> 
> Verifying the recommended fixes: When I run `echo $(pkg-config xkbcommon --variable=includedir)` it points to `/usr/include` When I run `echo $(pkg-config wayland-client --variable=includedir)` it also points to `/usr/include` Both files that the commands in @surprized's suggested fixes are indeed available in there (there's a folder for xkbcommon, and there are fiels for wayland-client).
> 
> Is there anything else I should be looking at for clues on how to fix this, or does anyone maybe know what is causing it?
> 
> EDIT: I did notice that after running `cmake -DCMAKE_INSTALL_PREFIX=/usr ..` inside the build folder, one thing that looked odd was the double-slash on `-- Found WaylandProtocols: //usr/share/wayland-protocols`, not sure what that's about or if it's related.

Ever resolve this? I'm having the same issue on Ubuntu 20.10

**Comment by Semperverus** [comment]
Unfortunately I have not, and I wound up switching to Arch, where it does compile correctly straight from the AUR.

**Comment by dobey** [comment]
> Ever resolve this? I'm having the same issue on Ubuntu 20.10

Ubuntu 20.10 is End of Life already. Please upgrade to 21.10, as 21.04 will be EOL in January.

Also, I've not seen this issue myself on debian testing.

**Comment by Semperverus** [comment]
> Also, I've not seen this issue myself on debian testing.

Try it on 32-bit.

**Comment by M-Kerr** [comment]
I just got it to work by building against Qt 5.15. This error occurred with the Ubuntu apt packages which are Qt 5.14 libs.

**Comment by M-Kerr** [comment]
> > Ever resolve this? I'm having the same issue on Ubuntu 20.10
> 
> Ubuntu 20.10 is End of Life already. Please upgrade to 21.10, as 21.04 will be EOL in January.
> 
> Also, I've not seen this issue myself on debian testing.

Project requires 20.10

**Comment by perezmeyer** [comment]
Happened to me on Debian unstable, I was missing qtwayland5-private-dev as a build dependency.

**Comment by avnotaklu** [comment]
Was having same issue on PopOs 22.04, fixed it with this package
sudo apt install qt6-base-private-dev
