### ISSUE TITLE
CMake fails to get results from PkgConfig

### ISSUE THREAD

**Issue by surprized** [maliit/framework#52]
My solution was to export the proper locations through external variables.
This patch [0000-fix_header_locations.txt](https://github.com/maliit/framework/files/5785552/0000-fix_header_locations.txt)
Or this should work as a temporary fix:

`target_include_directories(inputpanel-shell PUBLIC $ENV{wayland_private_headers_devel_includes})`
`target_include_directories(inputpanel-shell PUBLIC $ENV{xkbcommon_includes})`
`target_include_directories(maliit-common PUBLIC $ENV{xkbcommon_includes})`

Simon from the Plasma Mobile community proposed adding something similar to this at the lists:
`find_package(PkgConfig REQUIRED)` <-- already on the lists
`pkg_check_modules(IMGUI REQUIRED IMPORTED_TARGET GLOBAL imgui)`
`target_link_libraries(OgreOverlay PRIVATE PkgConfig::IMGUI)`

Same problem for maliit-keyboard2.

**Comment by jpetersen** [comment]
So the problem is the pkg-config is not found?

**Comment by surprized** [comment]
Hmm I should have been more clear with my issue...
I didn't really know much about CMake then; adding the include directories globaly was a workaround, looks like the wayland include dirs can be solved by adding `Wayland::Client` to `target_link_libraries` for `inputpanel-shell`, but for xkbcommon looks like it is not getting the result at all.
Apparently, some openSUSE packagers intentionally messed with the include directories for pkgconfig to make sure packages are reading them properly, so this is probably why it is only happening until now.

The build error is:
```
[    7s] /usr/include/qt5/QtXkbCommonSupport/5.15.2/QtXkbCommonSupport/private/qxkbcommon_p.h:59:10: fatal error: xkbcommon/xkbcommon.h: No such file or directory
[    7s]    59 | #include <xkbcommon/xkbcommon.h>
```
Inspecting the directory I see the header is there.
