### ISSUE TITLE
What's the holdup for 1.0?

### ISSUE THREAD

**Issue by KAMiKAZOW** [maliit/framework#53]
Maliit Framework is at version 0.99 since seven (!) years.
Why not release 1.0 already. Are you expecting any big changes before a Qt6 port what would require a major version jump anyway?

**Comment by jpetersen** [comment]
I am all good for a release. I think the only holdup was a good opportunity but I think with the interest from KDE Plasma that opportunity is now.

**Comment by jpetersen** [comment]
I am busy today, but will see to get a release out tomorrow.

**Comment by jpetersen** [comment]
Done.

**Comment by KAMiKAZOW** [comment]
Initial publicity on my part also already done: https://en.wikipedia.org/w/index.php?title=Maliit&type=revision&diff=1015592598&oldid=982781117

**Comment by KAMiKAZOW** [comment]
@jpetersen I've created https://build.opensuse.org/request/show/882712 based on work by @surprized. Could you accept it and perhaps make him maintainer as well? Seems weird to me that openSUSE's official Maliit dev repo is not used for Maliit packaging work.

**Comment by jpetersen** [comment]
@KAMiKAZOW Yes I will try, currently have trouble to get into my account on opensuse.org
