### ISSUE TITLE
(Maybe) another Ubuntu snag; XCB_LIBRARIES, despite libxcb1-dev being installed, doesn't seem to be detected

### ISSUE THREAD

**Issue by CheetahPixie** [maliit/framework#77]
Same Impish Indri install from the issue I filed against the keyboard repository, and here I am, now wondering whether this needs a specific library, or if anyone knows what package actually provides/sets this variable, since, as mentioned in the title, libxcb1-dev doesn't set it, nor does qtbase5-private-dev, despite including the Qt5XkbCommonSupportConfig.cmake file.

**Comment by dobey** [comment]
Can you please paste the specific error you're getting? It's not clear if anything is actually wrong from your summary and description.

Also, you might want to join `#maliit:matrix.org` on matrix, as github issues isn't really an efficient method for questions like this. :)

**Comment by CheetahPixie** [comment]
I'd do it if you lot had IRC. Is there a preferred way/place to paste the logs here?

**Comment by dobey** [comment]
> Is there a preferred way/place to paste the logs here?

Pastebin and link here, or an attachment, or just paste in a comment as block quote, if it's short enough.
