### ISSUE TITLE
Settings schema 'org.maliit.keyboard.maliit' is not installed

### ISSUE THREAD

**Issue by denglinglong** [maliit/framework#79]
Settings schema 'org.maliit.keyboard.maliit' is not installed  why?

**Comment by jpetersen** [comment]
The schema file https://github.com/maliit/keyboard/blob/master/data/schemas/org.maliit.keyboard.maliit.gschema.xml needs to be installed.

See also: https://askubuntu.com/questions/251712/how-can-i-install-a-gsettings-schema-without-root-privileges
