### ISSUE TITLE
Recommended type of window manager.

### ISSUE THREAD

**Issue by Langstonius** [maliit/framework#88]
I am attempting to get Maliit running on a tablet style device, but i've run across an odd issue that I didnt have on the desktop.
When the text input is activated (touched like one is going to type) the keyboard appears but it covers the entire application.
The keyboard shows up as it normally would in the lower third of the screen, but the remaining space is black and I can no longer see the application I was attempting to enter text into.
Are there any additional system requirements for Maliit server / keyboard system wise? Im a bit confused as to whats happening here.

**Comment by dobey** [comment]
What compositor/WM/etc… are you using? It sounds like a problem with the compositor perhaps.

**Comment by Langstonius** [comment]
Ive tried Blackbox and Fluxbox so far. I was hoping someone could point me to one they use already so I could rule out that portion of the problem.

**Comment by dobey** [comment]
Well it works fine under kwin_wayland (Plasma), and GNOME (at least on X11 for me). The WM really shouldn't matter so much.

**Comment by dobey** [comment]
I'll consider this answered for now.
